package classify

// Rules is the single source of truth. Order matters only among regex rules; word rules
// are looked up exactly (two-word first, then one-word).
var Rules = []Rule{
	// ---- waiting for workers / CI / leases
	{"gh run watch", WaitWorker, "ci", "waits for a GitHub Actions run"},
	{"gh pr checks", WaitWorker, "ci", "usually --watch; treated as CI wait"},
	{"gh workflow view", Code, "gh", ""},
	{"sleep", WaitWorker, "sleep", ""},
	{"re:(?s)\\bwhile\\b.*\\bsleep\\b", WaitWorker, "poll-loop", "shell polling loop"},
	{"re:(?s)\\buntil\\b.*\\bsleep\\b", WaitWorker, "poll-loop", ""},
	{"seg:^tail\\s+-[fF]\\b", WaitWorker, "tail-f", ""},

	// ---- release / deploy
	{"git push", Release, "git push", ""},
	{"gh pr create", Release, "pr create", ""},
	{"gh pr merge", Release, "pr merge", ""},
	{"gh pr ready", Release, "pr ready", ""},
	{"gh pr edit", Release, "pr edit", ""},
	{"gh pr comment", Release, "pr comment", ""},
	{"gh pr review", Release, "pr review", ""},
	{"gh pr close", Release, "pr close", ""},
	{"gh release", Release, "gh release", ""},
	{"gh run rerun", Release, "ci rerun", ""},
	{"gh run cancel", Release, "ci cancel", ""},
	{"glab mr create", Release, "glab mr", ""}, {"glab mr merge", Release, "glab mr", ""}, {"glab mr approve", Release, "mr approve", ""}, {"glab mr close", Release, "glab mr", ""}, {"glab mr update", Release, "glab mr", ""}, {"glab mr note", Release, "mr note", ""}, {"glab mr rebase", Release, "glab mr", ""},
	{"glab mr", Release, "glab mr", "create/merge/… ; reads split off below"},
	{"glab ci", Release, "glab ci", ""},
	{"glab release", Release, "glab release", ""},
	{"docker push", Release, "docker push", ""},
	{"kubectl apply", Release, "kubectl apply", ""},
	{"kubectl rollout", Release, "kubectl rollout", ""},
	{"helm upgrade", Release, "helm", ""},
	{"helm install", Release, "helm", ""},
	{"npm publish", Release, "publish", ""},
	{"cargo publish", Release, "publish", ""},
	{"xcrun devicectl device install", Release, "device install", ""},
	{"xcrun altool", Release, "app store upload", ""},
	{"xcrun notarytool", Release, "notarize", ""},
	{"fastlane", Release, "fastlane", ""},
	{"flyctl", Release, "fly", ""}, {"fly", Release, "fly", ""},
	{"vercel", Release, "vercel", ""}, {"netlify", Release, "netlify", ""},
	{"head:(^|[-_])(deploy|release|ship|publish|rollout)([-_.]|$)", Release, "deploy-script", "executable whose name contains deploy/release/ship/publish/rollout as a word"},
	{"head:(^|[-_])(build|compile|bundle)([-_.]|$)", Build, "build-script", "executable whose name contains build/compile/bundle as a word"},
	{"headpath:(^|/)(deploy|release|ship)[\\w.-]*/[^/]+$", Release, "deploy-script", "script located in a deploy*/release*/ship* directory"},
	{"head:(^|[-_])(worktree|checkout|branch)([-_.]|$)", Code, "vcs-script", "executable whose name says it manages worktrees/branches"},

	// ---- test
	{"swift test", Test, "swift test", ""},
	{"xcodebuild test", Test, "xcodebuild test", ""},
	{"xcodebuild test-without-building", Test, "xcodebuild test", ""},
	{"seg:^xcodebuild\\b.*\\s(test|test-without-building)(\\s|$)", Test, "xcodebuild test", "xcodebuild … test action"},
	{"pytest", Test, "pytest", ""},
	{"python -m pytest", Test, "pytest", ""}, {"python3 -m pytest", Test, "pytest", ""}, {"python -m unittest", Test, "unittest", ""}, {"python3 -m unittest", Test, "unittest", ""},
	{"python3 -m http.server", Infra, "http server", ""}, {"python -m http.server", Infra, "http server", ""},
	{"python3", Unknown, "python", "python without a recognizable script"}, {"python", Unknown, "python", ""}, {"node", Unknown, "node", ""}, {"ruby", Unknown, "ruby", ""}, {"perl", Unknown, "perl", ""},
	{"luau", Unknown, "luau", "luau / lua / Rscript / php without a recognizable script (a *.test.luau is a test by its name)"}, {"lua", Unknown, "lua", ""}, {"Rscript", Unknown, "Rscript", ""}, {"php", Unknown, "php", ""},
	{"python3 -m py_compile", Test, "syntax-check", "compiles sources to check their syntax, nothing runs"}, {"python -m py_compile", Test, "syntax-check", ""}, {"python3 -m compileall", Test, "syntax-check", ""}, {"python -m compileall", Test, "syntax-check", ""},
	{"python3 -m pip install", Build, "pip install", ""}, {"python -m pip install", Build, "pip install", ""}, {"python3 -m pip", Code, "pip", "pip list / show / freeze: a lookup"}, {"python -m pip", Code, "pip", ""}, {"pip", Code, "pip", "any other pip subcommand"}, {"pip3", Code, "pip", ""},
	{"python3 -m venv", Build, "venv", "creates a virtual environment (deps)"}, {"python -m venv", Build, "venv", ""}, {"uv venv", Build, "uv", ""},
	{"python3 -m ruff check", Test, "lint", ""}, {"python -m ruff check", Test, "lint", ""}, {"python3 -m ruff format", Code, "format", ""}, {"python -m ruff format", Code, "format", ""}, {"python3 -m ruff", Test, "lint", ""}, {"python -m ruff", Test, "lint", ""},
	{"python3 -m mypy", Test, "typecheck", ""}, {"python -m mypy", Test, "typecheck", ""}, {"python3 -m black", Code, "format", ""}, {"python -m black", Code, "format", ""},
	{"python3 -m uvicorn", Infra, "service", ""}, {"python -m uvicorn", Infra, "service", ""}, {"python3 -m gunicorn", Infra, "service", ""}, {"python -m gunicorn", Infra, "service", ""}, {"python3 -m flask run", Infra, "service", ""}, {"python -m flask run", Infra, "service", ""},
	{"python3 -m dmgbuild", Build, "dmgbuild", "packages a macOS disk image"}, {"python -m dmgbuild", Build, "dmgbuild", ""}, {"python3 -m build", Build, "python build", "PyPA build: an sdist / wheel"}, {"python -m build", Build, "python build", ""},
	{"python3 -m twine upload", Release, "publish", ""}, {"python -m twine upload", Release, "publish", ""}, {"twine upload", Release, "publish", ""},
	{"python3 -m json.tool", Code, "inspect", ""}, {"python -m json.tool", Code, "inspect", ""},
	{"python3 -m playwright install", Build, "playwright install", "downloads browsers (deps)"}, {"python -m playwright install", Build, "playwright install", ""}, {"python3 -m playwright", Test, "playwright", ""}, {"python -m playwright", Test, "playwright", ""}, {"playwright install", Build, "playwright install", ""},
	{"seg:^\"?\\$\\w+\"?\\s+-m\\s+(pytest|unittest)\\b", Test, "pytest", "\"$PY\" -m pytest: only python has -m pytest, whatever variable names the interpreter"},
	{"seg:^perl\\s+(?:-\\S+\\s+)*-[0-9]*[a-zA-Z]*i(?:\\.\\S*)?(?:\\s|$)", Code, "perl -i", "in-place edit (perl -pi / -0pi / -i.bak); -Ilib and -Mstrict are not the flag"},
	{"node --check", Test, "syntax-check", "parses without running"}, {"node -c", Test, "syntax-check", ""},
	{"npm test", Test, "npm test", ""},
	{"npm run test", Test, "npm test", "also npm run test:<variant> (unwrapHead)"},
	{"npm run lint", Test, "lint", ""}, {"npm run typecheck", Test, "typecheck", ""}, {"npm run check", Test, "check", ""}, {"npm run verify", Test, "check", ""},
	{"pnpm lint", Test, "lint", ""}, {"pnpm typecheck", Test, "typecheck", ""}, {"yarn lint", Test, "lint", ""}, {"yarn typecheck", Test, "typecheck", ""},
	{"oxlint", Test, "lint", ""}, {"biome check", Test, "lint", ""}, {"biome lint", Test, "lint", ""}, {"stylelint", Test, "lint", ""}, {"mypy", Test, "typecheck", ""}, {"pyright", Test, "typecheck", ""},
	{"shellcheck", Test, "lint", ""}, {"golangci-lint", Test, "lint", ""}, {"staticcheck", Test, "lint", ""}, {"shfmt", Code, "format", ""},
	{"pnpm test", Test, "pnpm test", ""}, {"pnpm run test", Test, "pnpm test", ""}, {"yarn test", Test, "yarn test", ""}, {"yarn run test", Test, "yarn test", ""},
	{"bun test", Test, "bun test", ""}, {"bun run test", Test, "bun test", ""}, {"bun run dev", Infra, "service", ""}, {"bun run start", Infra, "service", ""},
	{"deno test", Test, "deno test", ""}, {"deno bench", Test, "deno test", ""}, {"deno lint", Test, "lint", ""}, {"deno check", Test, "typecheck", ""}, {"deno fmt", Code, "format", ""}, {"deno run", Unknown, "deno run", "runs the product"},
	{"playwright", Test, "playwright", "also npx / pnpm dlx / bunx playwright (unwrapHead)"},
	{"playwright-cli", Test, "browser automation", ""},
	{"agent-browser", Test, "browser automation", ""},
	{"jest", Test, "jest", ""},
	{"vitest", Test, "vitest", ""},
	{"cargo test", Test, "cargo test", ""},
	{"go test", Test, "go test", ""},
	{"mvn test", Test, "mvn test", ""}, {"gradle test", Test, "gradle test", ""},
	{"ctest", Test, "ctest", "CMake's test runner"}, {"meson test", Test, "meson test", ""},
	{"seg:^cmake\\s+--build\\b.*\\s(--target|-t)\\s+(test|check)\\b", Test, "cmake test", "cmake --build … --target test / check"},
	{"bazel test", Test, "bazel test", ""}, {"bazelisk test", Test, "bazel test", ""}, {"buck2 test", Test, "buck2 test", ""},
	{"zig test", Test, "zig test", ""}, {"zig build test", Test, "zig test", ""},
	{"xcrun simctl", Test, "simulator", ""},
	{"xcrun devicectl device process launch", Test, "device run", "launches the app under test on a physical device (with --console it stays attached)"},
	{"xcrun xctrace", Test, "xctrace", ""},
	{"head:(^|[-_.])(test|tests|spec|e2e|smoke|qa)([-_.]|$)", Test, "test-script", "executable whose name contains test/spec/e2e/smoke/qa"},
	{"head:(^|[-_.])(preflight|precheck|check|checks|verify|verification|validate|validation|lint|audit|doctor|healthcheck|sanity|evaluate|evaluation|eval|bench|benchmark)([-_.]|$)", Test, "check-script", "executable whose name says it verifies or measures something (preflight/check/verify/validate/lint/audit/evaluate/bench)"},
	{"head:(^|[-_.])(start|serve|restart|launch)([-_.]|$)", Infra, "service", "executable whose name says it starts a service (start.sh, serve.mjs, restart-api.sh); a deploy/build/test/check word earlier in the table wins, and a bare `./dev` is a dispatcher, not a server"},
	{"headpath:(^|/)(qa|tests?|e2e|spec)/", Test, "test-script", "executable located under qa/ or tests/"},
	{"seg:^node\\s+--test\\b", Test, "node test", ""},
	{"seg:^(bash|sh|zsh)\\s+-n\\b", Test, "syntax-check", "shell syntax check"},

	// ---- build
	{"swift build", Build, "swift build", ""}, {"swift package", Build, "swift package", ""}, {"xcodegen", Build, "xcodegen", ""},
	{"swiftc", Build, "swiftc", "compiler invoked directly (also -typecheck)"}, {"xcrun swiftc", Build, "swiftc", ""}, {"swift run", Unknown, "swift run", "runs the built product"},
	{"xcodebuild", Build, "xcodebuild", "any xcodebuild not matched as test"},
	{"cargo build", Build, "cargo build", ""}, {"cargo check", Build, "cargo check", ""}, {"cargo clippy", Test, "lint", ""}, {"wasm-pack", Build, "wasm-pack", ""}, {"rustup", Infra, "rustup", "toolchain management"},
	{"rustc", Build, "rustc", "compiler invoked directly"},
	{"go run", Unknown, "go run", "runs the product (a -serve flag or a script name may say more)"}, {"cargo run", Unknown, "cargo run", ""}, {"bazel run", Unknown, "bazel run", ""}, {"bazelisk run", Unknown, "bazel run", ""}, {"dotnet run", Unknown, "dotnet run", ""},
	{"go build", Build, "go build", ""}, {"go vet", Test, "lint", ""}, {"go generate", Build, "go generate", ""}, {"go install", Build, "go install", "builds and installs the project's own packages (a module@version is a tool install, below)"},
	{"npm run build", Build, "npm build", "also npm run build:<variant> (unwrapHead)"}, {"pnpm build", Build, "pnpm build", ""}, {"pnpm run build", Build, "pnpm build", ""}, {"yarn build", Build, "yarn build", ""}, {"yarn run build", Build, "yarn build", ""},
	{"bun build", Build, "bun build", "bun's bundler"}, {"bun run build", Build, "bun build", ""}, {"deno compile", Build, "deno compile", ""}, {"deno task build", Build, "deno build", ""},
	{"next build", Build, "next build", ""}, {"webpack", Build, "webpack", "a bare webpack bundles (webpack serve is a service)"}, {"rollup", Build, "rollup", ""}, {"parcel build", Build, "parcel", ""},
	{"turbo build", Build, "turbo", ""}, {"turbo run build", Build, "turbo", ""}, {"nx build", Build, "nx", ""},
	{"npm pack", Build, "npm pack", ""},
	{"make", Build, "make", "make with no target, an unlisted target or a listed build target (matchMake); a dry run is `make -n` below"}, {"make build", Build, "make", ""}, {"make all", Build, "make", ""}, {"make compile", Build, "make", ""}, {"make install", Build, "make", ""},
	{"make dist", Build, "make", ""}, {"make package", Build, "make", ""}, {"make image", Build, "make", "a container image"}, {"make generate", Build, "make", ""}, {"make gen", Build, "make", ""}, {"make proto", Build, "make", ""}, {"make docs", Build, "make", "documentation build"},
	{"make -n", Code, "make query", "a dry run, a question, --version / --help: nothing is built"}, {"--version", Code, "version", "any tool with --version (-V, version) as its only argument, redirections aside"}, {"--help", Code, "help", "any tool with --help as its last argument (a lone -h on a tool the table does not know)"}, {"make help", Code, "make help", ""}, {"make logs", Code, "make logs", ""},
	{"make test", Test, "make test", ""}, {"make check", Test, "make test", ""}, {"make unit", Test, "make test", ""}, {"make integration", Test, "make test", ""}, {"make e2e", Test, "make test", ""}, {"make ci", Test, "make test", "the CI target: lint, test and build in one"},
	{"make bench", Test, "make test", ""}, {"make benchmark", Test, "make test", ""}, {"make coverage", Test, "make test", ""}, {"make cover", Test, "make test", ""}, {"make verify", Test, "make test", ""}, {"make validate", Test, "make test", ""},
	{"make lint", Test, "lint", ""}, {"make vet", Test, "lint", ""}, {"make typecheck", Test, "typecheck", ""}, {"make fmt", Code, "format", ""}, {"make format", Code, "format", ""},
	{"make run", Infra, "service", ""}, {"make serve", Infra, "service", ""}, {"make dev", Infra, "service", ""}, {"make start", Infra, "service", ""}, {"make up", Infra, "service", ""}, {"make watch", Infra, "service", ""}, {"make restart", Infra, "service", ""}, {"make down", Infra, "service", ""}, {"make stop", Infra, "service", ""},
	{"make clean", Infra, "cleanup", ""}, {"make distclean", Infra, "cleanup", ""}, {"make mrproper", Infra, "cleanup", ""}, {"make clobber", Infra, "cleanup", ""}, {"make deploy", Release, "deploy", ""}, {"make release", Release, "deploy", ""},
	{"cmake", Build, "cmake", "configure or --build"}, {"cmake -E", Code, "cmake -E", "cmake's command-line tool mode (copy, remove, echo)"}, {"meson", Build, "meson", "setup / compile"}, {"scons", Build, "scons", ""},
	{"ninja", Build, "ninja", "no target, the default goal, or a listed build target (matchTargets)"}, {"ninja all", Build, "ninja", ""}, {"ninja install", Build, "ninja", ""}, {"ninja test", Test, "ninja test", ""}, {"ninja check", Test, "ninja test", ""},
	{"ninja clean", Infra, "cleanup", ""}, {"ninja -t clean", Infra, "cleanup", ""}, {"ninja -t", Code, "ninja query", "a sub-tool: targets, query, deps, graph, browse"}, {"ninja -n", Code, "ninja query", "a dry run, --version / --help"},
	{"bazel build", Build, "bazel", ""}, {"bazelisk build", Build, "bazel", ""}, {"bazel query", Code, "bazel", ""}, {"bazelisk query", Code, "bazel", ""}, {"buck2 build", Build, "buck2", ""},
	{"gcc", Build, "cc", "C / C++ compiler invoked directly"}, {"g++", Build, "cc", ""}, {"cc", Build, "cc", ""}, {"c++", Build, "cc", ""}, {"clang", Build, "cc", ""}, {"clang++", Build, "cc", ""}, {"nvcc", Build, "cc", ""}, {"emcc", Build, "cc", ""},
	{"ld", Build, "link", "linker / archiver invoked directly"}, {"ar", Build, "link", ""},
	{"configure", Build, "configure", "./configure and the autotools that write it"}, {"autoreconf", Build, "configure", ""}, {"autoconf", Build, "configure", ""}, {"automake", Build, "configure", ""}, {"libtoolize", Build, "configure", ""},
	{"zig build", Build, "zig build", ""},
	{"tsc", Build, "tsc", "emits JavaScript"}, {"seg:^(npx\\s+)?tsc\\b.*\\s--noEmit\\b", Test, "typecheck", "tsc --noEmit: a type check, nothing is emitted (test outranks the build word rule)"}, {"vite build", Build, "vite", ""}, {"esbuild", Build, "esbuild", ""},
	{"docker build", Build, "docker build", ""}, {"docker compose build", Build, "docker build", ""}, {"docker buildx", Build, "docker build", ""},
	{"gradle", Build, "gradle", ""}, {"mvn", Build, "mvn", ""},

	// ---- build: dependency installation (the deps sub-row; every kind here is in DepsKinds)
	{"npm ci", Build, "npm install", ""}, {"npm install", Build, "npm install", ""}, {"npm i", Build, "npm install", ""}, {"npm add", Build, "npm install", ""},
	{"pnpm install", Build, "pnpm install", ""}, {"pnpm i", Build, "pnpm install", ""}, {"pnpm add", Build, "pnpm install", ""},
	{"yarn", Build, "yarn install", "a bare yarn installs"}, {"yarn install", Build, "yarn install", ""}, {"yarn add", Build, "yarn install", ""},
	{"bun install", Build, "bun install", ""}, {"bun add", Build, "bun install", ""},
	{"pip install", Build, "pip install", ""}, {"pip3 install", Build, "pip install", ""}, {"uv sync", Build, "uv", ""}, {"uv add", Build, "uv", ""}, {"uv pip install", Build, "uv", ""}, {"uv lock", Build, "uv", ""},
	{"poetry install", Build, "poetry install", ""}, {"poetry add", Build, "poetry install", ""}, {"poetry lock", Build, "poetry install", ""}, {"pipenv install", Build, "pipenv install", ""},
	{"go mod", Build, "go mod", ""}, {"go get", Build, "go get", ""}, {"seg:^go install\\b.*\\S@\\S", Build, "go install tool", "go install pkg@version: a tool from a module, not the project"},
	{"cargo add", Build, "cargo deps", ""}, {"cargo fetch", Build, "cargo deps", ""}, {"cargo update", Build, "cargo deps", ""}, {"cargo vendor", Build, "cargo deps", ""}, {"cargo install", Build, "cargo install", "a crate's binary, compiled locally"},
	{"bundle", Build, "bundle install", "Ruby's bundler: install / update / outdated (its name would otherwise read as a build script)"},
	{"pod install", Build, "pod install", ""}, {"pod update", Build, "pod install", ""}, {"carthage bootstrap", Build, "carthage", ""}, {"carthage update", Build, "carthage", ""}, {"mint install", Build, "mint install", ""},
	{"swift package resolve", Build, "swift package resolve", ""}, {"swift package update", Build, "swift package resolve", ""},
	{"make deps", Build, "make deps", ""}, {"make vendor", Build, "make deps", ""}, {"make setup", Infra, "setup-script", "like ./setup.sh: environment setup"}, {"make bootstrap", Infra, "setup-script", ""},

	// ---- infrastructure: long-running local services
	{"npm start", Infra, "service", "dev server / app process"}, {"npm run dev", Infra, "service", ""}, {"npm run serve", Infra, "service", ""}, {"npm run start", Infra, "service", ""}, {"npm run preview", Infra, "service", ""},
	{"pnpm dev", Infra, "service", ""}, {"yarn dev", Infra, "service", ""}, {"pnpm start", Infra, "service", ""}, {"yarn start", Infra, "service", ""},
	{"vite", Infra, "service", "vite dev server"}, {"vite dev", Infra, "service", ""}, {"vite serve", Infra, "service", ""}, {"vite preview", Infra, "service", ""},
	{"vinext dev", Infra, "service", ""}, {"next dev", Infra, "service", ""}, {"next start", Infra, "service", ""}, {"nuxt dev", Infra, "service", ""}, {"astro dev", Infra, "service", ""}, {"webpack serve", Infra, "service", ""}, {"nodemon", Infra, "service", ""}, {"http-server", Infra, "service", ""}, {"serve", Infra, "service", ""},
	{"flask run", Infra, "service", ""}, {"uvicorn", Infra, "service", ""}, {"gunicorn", Infra, "service", ""}, {"rails server", Infra, "service", ""}, {"php -S", Infra, "service", ""},
	{"docker", Infra, "docker", "any other docker subcommand"},
	{"docker compose", Infra, "docker compose", ""},
	{"kubectl", Infra, "kubectl", ""},
	{"ssh", Infra, "ssh", ""},
	{"scp", Infra, "scp", ""}, {"rsync", Infra, "rsync", ""},
	{"kill", Infra, "kill", ""}, {"pkill", Infra, "kill", ""}, {"killall", Infra, "kill", ""},
	{"brew", Infra, "brew", ""}, {"apt", Infra, "apt", ""}, {"apt-get", Infra, "apt", ""},
	{"systemctl", Infra, "systemctl", ""}, {"launchctl", Infra, "launchctl", ""}, {"journalctl", Infra, "journalctl", ""},
	{"chmod", Infra, "chmod", ""}, {"chown", Infra, "chown", ""},
	{"open", Infra, "open", "macOS open"}, {"osascript", Infra, "osascript", ""},
	{"xcrun devicectl", Infra, "devicectl", ""},
	{"xcrun", Infra, "xcrun", ""},
	{"caffeinate", Infra, "caffeinate", ""},
	{"log", Infra, "diagnostics", "macOS unified log"}, {"sample", Infra, "diagnostics", ""}, {"spindump", Infra, "diagnostics", ""}, {"dtrace", Infra, "diagnostics", ""},
	{"ffmpeg", Infra, "media", ""}, {"qlmanage", Infra, "media", ""}, {"pdftotext", Infra, "media", ""}, {"pdfinfo", Infra, "media", ""}, {"cairosvg", Infra, "media", ""}, {"ffprobe", Infra, "media", ""}, {"sips", Infra, "media", ""}, {"magick", Infra, "media", ""}, {"convert", Infra, "media", ""},
	{"head:(^|[-_])(install|setup|bootstrap|provision)([-_.]|$)", Infra, "setup-script", "executable whose name says it installs/sets up something"},
	{"seg:^rm\\s+(?:--?\\S+\\s+)*(?:-[A-Za-z]*[rR][A-Za-z]*|--recursive)(?:\\s|$)", Infra, "cleanup", "recursive delete"}, {"rm", Code, "rm", "a file delete: a lookup-grade step, not a change of the sources (a recursive rm is cleanup)"},
	{"head:^(cleanup|clean|teardown|reset)[\\w.-]*\\.(sh|py)$", Infra, "cleanup-script", ""},

	// ---- develop (edits, local VCS, formatting)
	{"git add", Code, "git add", ""}, {"git commit", Code, "git commit", ""},
	{"git switch", Code, "git switch", ""}, {"git checkout", Code, "git checkout", ""},
	{"git stash", Code, "git stash", ""}, {"git rebase", Code, "git rebase", ""},
	{"git merge", Code, "git merge", ""}, {"git restore", Code, "git restore", ""},
	{"git reset", Code, "git reset", ""}, {"git rm", Code, "git rm", ""}, {"git mv", Code, "git mv", ""},
	{"git worktree", Code, "git worktree", ""}, {"git fetch", Code, "git fetch", ""}, {"git pull", Code, "git pull", ""},
	{"git cherry-pick", Code, "git cherry-pick", ""}, {"git apply", Code, "git apply", ""}, {"git tag", Code, "git tag", ""},
	{"git clone", Code, "git clone", ""}, {"git init", Code, "git init", ""}, {"git submodule", Code, "git submodule", ""},
	{"gofmt", Code, "format", ""}, {"prettier", Code, "format", ""},
	{"oxfmt", Code, "format", ""}, {"black", Code, "format", ""}, {"ruff format", Code, "format", ""}, {"ruff", Test, "lint", "static verification"}, {"eslint", Test, "lint", ""},
	{"swiftformat", Code, "format", ""}, {"swiftlint", Test, "lint", ""}, {"cargo fmt", Code, "format", ""},
	{"mkdir", Code, "mkdir", ""}, {"cp", Code, "cp", ""}, {"mv", Code, "mv", ""}, {"touch", Code, "touch", ""}, {"ln", Code, "ln", ""},
	{"seg:^sed\\s+-i\\b", Code, "sed -i", "in-place edit"},
	{"seg:^cat\\s*>{1,2}\\s*\\S", Code, "write-file", "cat > file <<EOF"},
	{"seg:^tee\\s+(-a\\s+)?\\S", Code, "write-file", ""},

	// ---- explore (read / search / inspect)
	{"cat", Code, "read", ""}, {"sed", Code, "read", "sed -n …p"}, {"head", Code, "read", ""}, {"tail", Code, "read", ""},
	{"less", Code, "read", ""}, {"more", Code, "read", ""}, {"nl", Code, "read", ""}, {"bat", Code, "read", ""},
	{"rg", Code, "search", ""}, {"grep", Code, "search", ""}, {"egrep", Code, "search", ""}, {"fgrep", Code, "search", ""}, {"ag", Code, "search", ""}, {"ack", Code, "search", ""},
	{"find", Code, "list", ""}, {"fd", Code, "list", ""}, {"ls", Code, "list", ""}, {"tree", Code, "list", ""}, {"stat", Code, "list", ""}, {"file", Code, "list", ""},
	{"wc", Code, "inspect", ""}, {"jq", Code, "inspect", ""}, {"yq", Code, "inspect", ""}, {"sort", Code, "inspect", ""}, {"uniq", Code, "inspect", ""}, {"cut", Code, "inspect", ""}, {"awk", Code, "inspect", ""}, {"tr", Code, "inspect", ""}, {"diff", Code, "inspect", ""}, {"cmp", Code, "inspect", ""}, {"strings", Code, "inspect", ""}, {"od", Code, "inspect", ""}, {"xxd", Code, "inspect", ""}, {"md5", Code, "inspect", ""}, {"shasum", Code, "inspect", ""}, {"sha256sum", Code, "inspect", ""},
	{"echo", Code, "shell", ""}, {"printf", Code, "shell", ""}, {"true", Code, "shell", ""}, {"test", Code, "probe", "exit 1 = the condition is false"}, {"[", Code, "probe", ""}, {"pwd", Code, "shell", ""}, {"cd", Code, "shell", ""}, {"which", Code, "probe", "exit 1 = not installed"}, {"type", Code, "probe", ""}, {"command -v", Code, "probe", "the builtin form of which"}, {"env", Code, "shell", ""}, {"date", Code, "shell", ""}, {"export", Code, "shell", ""}, {"set", Code, "shell", ""}, {"uname", Code, "shell", ""}, {"whoami", Code, "shell", ""}, {"hostname", Code, "shell", ""}, {"id", Code, "shell", ""}, {"basename", Code, "shell", ""}, {"dirname", Code, "shell", ""}, {"realpath", Code, "shell", ""}, {"read", Code, "shell", ""}, {"exit", Code, "shell", ""}, {"local", Code, "shell", ""}, {"declare", Code, "shell", ""}, {"shift", Code, "shell", ""}, {"return", Code, "shell", ""}, {"break", Code, "shell", ""}, {"continue", Code, "shell", ""}, {"trap", Code, "shell", ""}, {"wait", WaitWorker, "wait", "shell wait for background jobs"},
	{"ps", Code, "process", ""}, {"lsof", Code, "process", ""}, {"pgrep", Code, "process", ""}, {"top", Code, "process", ""}, {"df", Code, "system", ""}, {"du", Code, "system", ""}, {"uptime", Code, "system", ""}, {"sw_vers", Code, "system", ""}, {"system_profiler", Code, "system", ""}, {"defaults", Code, "system", ""}, {"plutil", Code, "inspect", ""}, {"mdls", Code, "inspect", ""},
	{"git status", Code, "git status", ""}, {"git diff", Code, "git diff", ""}, {"git log", Code, "git log", ""}, {"git show", Code, "git show", ""}, {"git blame", Code, "git blame", ""},
	{"git rev-parse", Code, "git", ""}, {"git branch", Code, "git branch", ""}, {"git remote", Code, "git", ""}, {"git ls-files", Code, "git", ""}, {"git grep", Code, "search", ""}, {"git describe", Code, "git", ""}, {"git config", Code, "git", ""}, {"git rev-list", Code, "git", ""}, {"git shortlog", Code, "git", ""}, {"git cat-file", Code, "git", ""}, {"git ls-remote", Code, "git", ""}, {"git name-rev", Code, "git", ""}, {"git stash list", Code, "git", ""}, {"git worktree list", Code, "git", ""}, {"git -C", Code, "git", "resolved by next word"}, {"git", Code, "git", "any other git subcommand (local)"}, {"git merge-base", Code, "git", ""}, {"git check-ignore", Code, "git", ""},
	{"gh pr view", Code, "gh", ""}, {"gh pr list", Code, "gh", ""}, {"gh pr diff", Code, "gh", ""}, {"gh pr status", Code, "gh", ""}, {"gh api", Code, "gh api", ""}, {"gh run view", Code, "gh", ""}, {"gh run list", Code, "gh", ""}, {"gh issue", Code, "gh", ""}, {"gh repo view", Code, "gh", ""}, {"gh auth", Code, "gh", ""}, {"gh", Code, "gh", "other gh"},
	{"glab mr view", Code, "glab mr", ""}, {"glab mr list", Code, "glab mr", ""}, {"glab mr diff", Code, "glab mr", ""}, {"glab mr checkout", Code, "glab mr", ""}, {"glab mr todo", Code, "glab mr", ""},
	{"glab api", Code, "glab api", "GitLab REST call (read or write); like gh api it stays code — an MR comment/resolve is review work, not release"}, {"glab ci view", Code, "glab ci", ""}, {"glab ci status", Code, "glab ci", ""}, {"glab ci get", Code, "glab ci", ""}, {"glab ci list", Code, "glab ci", ""}, {"glab ci trace", Code, "glab ci", ""}, {"glab auth", Code, "glab", ""}, {"glab config", Code, "glab", ""}, {"glab alias", Code, "glab", ""}, {"glab repo", Code, "glab", ""}, {"glab", Code, "glab", "any other glab subcommand (local/read)"},
	{"on-cli", Infra, "remote vm", "imunify VM/runner management"}, {"onevm", Infra, "remote vm", ""},
	{"sqlite3", Code, "sqlite", ""}, {"psql", Code, "sql", ""}, {"mysql", Code, "sql", ""},
	{"curl", Code, "http", ""}, {"wget", Code, "http", ""}, {"http", Code, "http", ""}, {"dig", Code, "dns", ""}, {"nslookup", Code, "dns", ""}, {"ping", Code, "net", ""}, {"nc", Code, "net", ""},
	{"node --version", Code, "version", ""}, {"python3 --version", Code, "version", ""}, {"go version", Code, "version", ""}, {"swift --version", Code, "version", ""},
	{"go env", Code, "go env", ""}, {"go list", Code, "go list", ""}, {"go doc", Code, "go doc", ""}, {"cargo metadata", Code, "cargo", ""}, {"npm ls", Code, "npm", ""}, {"npm view", Code, "npm", ""}, {"npm run", Unknown, "npm run", "arbitrary script (build / test variants are their base script, unwrapHead)"},
	{"xcrun devicectl device info", Code, "devicectl", ""}, {"xcrun devicectl list", Code, "devicectl", ""}, {"xcrun simctl list", Code, "simulator", ""},
	{"xcode-select", Code, "xcode", ""}, {"xcodebuild -list", Code, "xcode", ""}, {"xcodebuild -showsdks", Code, "xcode", ""}, {"xcodebuild -version", Code, "xcode", ""},
	{"docker ps", Code, "docker", ""}, {"docker info", Code, "docker", ""}, {"docker version", Code, "docker", ""}, {"docker events", Code, "docker", ""}, {"docker images", Code, "docker", ""}, {"docker image ls", Code, "docker", ""}, {"docker image list", Code, "docker", ""}, {"docker image inspect", Code, "docker", ""}, {"docker container ls", Code, "docker", ""}, {"docker container list", Code, "docker", ""}, {"docker container inspect", Code, "docker", ""}, {"docker volume inspect", Code, "docker", ""}, {"docker network inspect", Code, "docker", ""}, {"docker compose ls", Code, "docker", ""}, {"docker logs", Code, "docker logs", ""}, {"docker inspect", Code, "docker", ""}, {"docker compose ps", Code, "docker", ""}, {"docker compose logs", Code, "docker logs", ""}, {"docker network ls", Code, "docker", ""}, {"docker volume ls", Code, "docker", ""}, {"docker system df", Code, "docker", ""},
	{"kubectl get", Code, "kubectl", ""}, {"kubectl describe", Code, "kubectl describe", ""}, {"kubectl logs", Code, "kubectl logs", ""},
	{"security find-identity", Code, "codesign", ""}, {"codesign", Code, "codesign", ""}, {"spctl", Code, "codesign", ""},
	{"base64", Code, "inspect", ""},

	// ---- rows from the 2026-09-21 unknown-command sweep (docs/ARCHITECTURE.md §13)
	{"hdiutil create", Build, "dmg", "packages a disk image"}, {"hdiutil", Infra, "hdiutil", "attach / detach / verify a disk image"},
	{"ditto", Code, "cp", ""}, {"rmdir", Code, "rm", ""}, {"trash", Code, "rm", ""},
	{"umask", Code, "shell", ""}, {"unset", Code, "shell", ""}, {"shopt", Code, "shell", ""}, {"source", Code, "shell", "a venv activation or an env file; a named script is judged by its name (matchHead)"}, {".", Code, "shell", ""}, {":", Code, "shell", "the null command (`: > file` truncates)"},
	{"alias", Code, "shell", ""}, {"ulimit", Code, "shell", ""}, {"pushd", Code, "shell", ""}, {"popd", Code, "shell", ""}, {"dirs", Code, "shell", ""}, {"mktemp", Code, "shell", ""}, {"readlink", Code, "shell", ""}, {"seq", Code, "shell", ""}, {"let", Code, "shell", ""}, {"readonly", Code, "shell", ""}, {"typeset", Code, "shell", ""}, {"getopts", Code, "shell", ""}, {"hash", Code, "shell", ""}, {"sync", Code, "shell", ""},
	{"[[", Code, "probe", "the bash conditional: exit 1 = the condition is false"},
	{"xmllint --noout", Test, "lint", "well-formedness / schema check"}, {"xmllint", Code, "inspect", "an XPath query or a reformat"},
	{"dns-sd", Code, "dns", ""}, {"host", Code, "dns", ""}, {"whois", Code, "dns", ""}, {"arp", Code, "net", ""}, {"nettop", Code, "net", ""}, {"netstat", Code, "net", ""}, {"ifconfig", Code, "net", ""}, {"traceroute", Code, "net", ""}, {"ss", Code, "net", ""},
	{"screencapture", Code, "image", "a screenshot taken to look at"},
	{"identify", Code, "inspect", "ImageMagick identify: reads image metadata"}, {"md5sum", Code, "inspect", ""}, {"sha1sum", Code, "inspect", ""}, {"cksum", Code, "inspect", ""}, {"comm", Code, "inspect", ""}, {"join", Code, "inspect", ""}, {"paste", Code, "inspect", ""}, {"column", Code, "inspect", ""}, {"fold", Code, "inspect", ""}, {"rev", Code, "inspect", ""}, {"tac", Code, "inspect", ""}, {"bc", Code, "inspect", ""}, {"expr", Code, "inspect", ""}, {"numfmt", Code, "inspect", ""},
	{"pdftoppm", Infra, "media", ""}, {"pdftocairo", Infra, "media", ""}, {"qpdf", Infra, "media", ""}, {"mutool", Infra, "media", ""}, {"gs", Infra, "media", "Ghostscript"}, {"pdfunite", Infra, "media", ""}, {"pdfseparate", Infra, "media", ""}, {"exiftool", Infra, "media", ""},
	{"security find-generic-password", Code, "keychain", "keychain reads: a query"}, {"security find-internet-password", Code, "keychain", ""}, {"security find-certificate", Code, "keychain", ""}, {"security list-keychains", Code, "keychain", ""}, {"security show-keychain-info", Code, "keychain", ""}, {"security default-keychain", Code, "keychain", ""}, {"security dump-keychain", Code, "keychain", ""},
	{"security", Infra, "keychain", "add-generic-password / import / create-keychain / set-key-partition-list / unlock-keychain: a change"},
	{"ssh-add -l", Code, "ssh-agent", "lists the agent's keys"}, {"ssh-add -L", Code, "ssh-agent", ""}, {"ssh-add", Infra, "ssh keys", ""}, {"ssh-keygen", Infra, "ssh keys", ""}, {"ssh-copy-id", Infra, "ssh keys", ""}, {"ssh-keyscan", Infra, "ssh keys", ""},
	{"sysctl", Code, "system", ""}, {"ioreg", Code, "system", ""}, {"scutil --get", Code, "system", ""}, {"diskutil info", Code, "system", ""}, {"diskutil list", Code, "system", ""}, {"dscl . -read", Code, "system", ""}, {"kmutil showloaded", Code, "system", ""}, {"DevToolsSecurity -status", Code, "system", ""}, {"pmset -g", Code, "system", ""}, {"nvram -p", Code, "system", ""}, {"tmutil status", Code, "system", ""}, {"csrutil status", Code, "system", ""},
	{"diskutil", Infra, "system admin", "mount / unmount / erase / repair"}, {"dscl", Infra, "system admin", ""}, {"kmutil", Infra, "system admin", ""}, {"dscacheutil", Infra, "system admin", ""}, {"lsregister", Infra, "system admin", ""}, {"pmset", Infra, "system admin", ""}, {"nvram", Infra, "system admin", ""}, {"DevToolsSecurity", Infra, "system admin", ""}, {"scutil", Infra, "system admin", ""}, {"networksetup", Infra, "system admin", ""}, {"tmutil", Infra, "system admin", ""}, {"csrutil", Infra, "system admin", ""}, {"softwareupdate", Infra, "system admin", ""},
	{"man", Code, "read", ""}, {"tldr", Code, "read", ""}, {"apropos", Code, "read", ""}, {"whatis", Code, "read", ""},
	{"lipo -create", Build, "lipo", "assembles a universal binary"}, {"lipo -thin", Build, "lipo", ""}, {"lipo -extract", Build, "lipo", ""}, {"lipo", Code, "inspect", "-info / -archs: reads the slices"},
	{"PlistBuddy", Code, "inspect", "-c Print: reads a plist"}, {"seg:^\\S*PlistBuddy\\b.*\\s-c\\s+[\"']?(Set|Add|Delete|Merge|Import|Copy)\\b", Code, "edit", "PlistBuddy -c Set / Add / Delete …: edits the plist"},
	{"tar", Code, "archive", "pack / unpack / list an archive"}, {"zip", Code, "archive", ""}, {"unzip", Code, "archive", ""}, {"gzip", Code, "archive", ""}, {"gunzip", Code, "archive", ""}, {"zstd", Code, "archive", ""}, {"xz", Code, "archive", ""}, {"bzip2", Code, "archive", ""}, {"7z", Code, "archive", ""}, {"7za", Code, "archive", ""},
	{"caddy run", Infra, "service", ""}, {"caddy start", Infra, "service", ""}, {"caddy stop", Infra, "service", ""}, {"caddy reload", Infra, "service", ""}, {"caddy validate", Test, "lint", "config validation"}, {"caddy fmt", Code, "format", ""}, {"caddy", Code, "caddy", "version / list-modules / adapt: lookups"},
	{"actionlint", Test, "lint", ""}, {"hadolint", Test, "lint", ""}, {"yamllint", Test, "lint", ""}, {"markdownlint", Test, "lint", ""}, {"markdownlint-cli2", Test, "lint", ""}, {"htmlhint", Test, "lint", ""}, {"jsonlint", Test, "lint", ""}, {"vale", Test, "lint", ""},
	{"goimports", Code, "format", "-l lists, -w writes: a formatter either way, like gofmt"}, {"go clean", Infra, "cleanup", ""},
	{"codex", Code, "harness cli", "the Codex CLI itself: plugin / config / lookups"}, {"codex exec", WaitWorker, "agent", "a headless Codex run: the caller waits for another agent"}, {"claude", Code, "harness cli", ""}, {"claude -p", WaitWorker, "agent", "a headless Claude Code run"},
	{"rokit install", Build, "rokit", "Roblox toolchain manager: installs the pinned tools (deps)"}, {"rokit add", Build, "rokit", ""}, {"rokit self-install", Build, "rokit", ""}, {"rokit self-update", Build, "rokit", ""}, {"rokit trust", Build, "rokit", ""}, {"rokit update", Build, "rokit", ""}, {"rokit", Code, "rokit", "list / system-info: lookups; `rokit run <tool>` is the tool (unwrapHead)"},
	{"rojo serve", Infra, "service", "Rojo's live-sync server"}, {"rojo build", Build, "rojo", "builds a place file"}, {"rojo sourcemap", Build, "rojo", ""}, {"rojo upload", Release, "publish", ""}, {"rojo plugin", Infra, "setup-script", "installs the Studio plugin"}, {"rojo", Code, "rojo", "init / fmt-project / doc: lookups and scaffolds"},
	{"npm run e2e", Test, "npm e2e", "also npm run e2e:<variant> (unwrapHead)"}, {"npm run bench", Test, "bench", "also bench:<variant>"}, {"npm run benchmark", Test, "bench", ""}, {"pnpm e2e", Test, "npm e2e", ""}, {"pnpm run e2e", Test, "npm e2e", ""}, {"yarn e2e", Test, "npm e2e", ""}, {"yarn run e2e", Test, "npm e2e", ""}, {"bun run e2e", Test, "npm e2e", ""}, {"pnpm bench", Test, "bench", ""}, {"yarn bench", Test, "bench", ""},
	{"npm audit", Test, "audit", "a dependency vulnerability check with a verdict"}, {"npm audit fix", Build, "npm install", "rewrites the lockfile"}, {"pnpm audit", Test, "audit", ""}, {"yarn audit", Test, "audit", ""},
	{"npm uninstall", Build, "npm install", "removes / updates dependencies (deps)"}, {"npm remove", Build, "npm install", ""}, {"npm rm", Build, "npm install", ""}, {"npm un", Build, "npm install", ""}, {"npm update", Build, "npm install", ""}, {"npm prune", Build, "npm install", ""}, {"npm dedupe", Build, "npm install", ""}, {"npm link", Build, "npm install", ""},
	{"pnpm remove", Build, "pnpm install", ""}, {"pnpm update", Build, "pnpm install", ""}, {"pnpm prune", Build, "pnpm install", ""}, {"yarn remove", Build, "yarn install", ""}, {"yarn upgrade", Build, "yarn install", ""},
	{"npm run format", Code, "format", "also format:<variant> / fmt (unwrapHead)"}, {"npm run fmt", Code, "format", ""}, {"pnpm format", Code, "format", ""}, {"pnpm run format", Code, "format", ""}, {"yarn format", Code, "format", ""}, {"bun run format", Code, "format", ""}, {"npm root", Code, "npm", "prints a path"}, {"npm prefix", Code, "npm", ""}, {"npm config", Code, "npm", ""},
	{"npm create", Code, "npm init", "scaffolds a project: files, not a build"}, {"npm init", Code, "npm init", ""}, {"pnpm create", Code, "npm init", ""}, {"yarn create", Code, "npm init", ""},
	{"linear issue view", Code, "linear query", "Linear CLI reads: a query"}, {"linear issue list", Code, "linear query", ""}, {"linear issue query", Code, "linear query", ""}, {"linear issue search", Code, "linear query", ""}, {"linear", Code, "linear", "issue create / update / comment / relation: the tracker written"}, {"jira", Code, "jira", ""},
	{"headpath:\\.app/Contents/MacOS/[^/]+$", Unknown, "app run", "the built app bundle launched directly: runs the product, like `swift run` (pin it in the overlay)"},
}
